= poor-mans-lambda-test
:toc:
:toc-placement: preamble
// also update version in pom.xml example
:lambdatestversion: 0.0.3

image:https://travis-ci.org/lefou/poor-mans-lambda-test.svg?branch=master["Build Status", link="https://travis-ci.org/lefou/poor-mans-lambda-test"]
image:https://www.codacy.com/project/badge/b05b1dc99f98423eb05862de7fcf3662["Codacy Badge", link="https://www.codacy.com/public/lepetitfou_3463/poor-mans-lambda-test"]

Minimal Java8 Lambda enabled testing for TestNG (and later maybe JUnit).

== Motivation

When constrained to work in a Java-only toolchain, I really miss my ScalaTest.
I tried some lambda enabled test frameworks, but until now,
I did not find a suitable solution without compromizing the integration benefits.

Thus I decided to hack a really small and generic base class that basically allows me write tests easier.
I avoided to develop a completely new test stack,
so for asserts and the like the tools of the underlying test framework (currently TestNG) are used. 

Most important features (beside all those you gain from using TestNG already) are:

* No longer requied to have each test in a separate method
* Meaningful names for tests
* Easy to write data-centric tests (e.g. generate as much test cases as you need in a loop)
* Easy to intercept exceptions
* Easy to mark pending tests
* Nice colored output per test case


== How to write tests

Here you see a basic test example, which produces a TestNG test class.
You need to extend from class `de.tobiasroeser.lambdatest.testng.FreeSpec`.

[source,java]
----
package org.example;

import static org.testng.Assert.assertEquals;

import de.tobiasroeser.lambdatest.testng.FreeSpec;

class SimpleTest extends FreeSpec {{

  test("1 + 1 = 2", () -> {
    assertEquals(1 + 1, 2);
  });

  test("a pending test", () -> pending());

  test("divide by zero", () -> {
    int a = 2;
    int b = 0;
    intercept(ArithmeticException.class, () -> {
      int c = a / b;
    });
  });

}}
----

The methods `test`, `pending` and `intercept` are provided by `FreeSpec`
whereas the usual `assertXXX` methods are provided by TestNG (in this case from `org.testng.Assert`).

The output of the test suite above whould look like this (executed via `mvn test`):

----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.example.SimpleTest
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@759ebb3d
Running 3 tests in org.example.SimpleTest:
-- SUCCESS SimpleTest: 1 + 1 = 2
-- SKIPPED SimpleTest: a pending test (pending)
-- SUCCESS SimpleTest: divide by zero
Tests run: 3, Faiulres: 0, Errors: 0, Skipped: 0, Time elapsed: 0.395 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

== Working on Java7 or below

This project does not use any Java 8 API!
Of course a Java 8 compiler needs to be used (to use the nice Closures) but afterwards postprocessing with tools like RetroLambda is supported.
If done so, you can run these test with older version of Java, e.g. Java7 or Java6.


== Licence

This project is published under the http://www.apache.org/licenses/LICENSE-2.0.txt[Apache Licence Version 2.0].

== Maven

To use this project in your Maven project:

[source,xml]
----
<repositories>
  <repository>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
    <id>bintray-lefou-poor-mans-lambda-test</id>
    <name>bintray-lefou-poor-mans-lambda-test</name>
    <url>http://dl.bintray.com/lefou/poor-mans-lambda-test</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>de.tobiasroeser</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>0.0.3</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.8</version>
    <scope>test</scope>
  </dependency>
</dependencies>
----

== Changelog

=== 0.0.3 - 2014-11-16

* Fixed issue with missapplied close of STDOUT stream
* Fixed bug preventing from TestNG seeing pending tests as skipped
* de.tobiasroeser.lambdatest.testng.FreeSpec class no longer inherits org.testng.Assert

=== 0.0.2 - 2014-10-18

* Colored output
* Added support to match exception messages with regex in intecept

=== 0.0.1 - 2014-10-15

* First release
