= (Poor Mans) Lambda Test
:toc:
:toc-placement: preamble
// also update version in pom.xml example (2x)
:lambdatestversion: 0.1.0

image:https://travis-ci.org/lefou/poor-mans-lambda-test.svg?branch=master["Build Status", link="https://travis-ci.org/lefou/poor-mans-lambda-test"]
image:https://img.shields.io/codacy/b05b1dc99f98423eb05862de7fcf3662.svg["Codacy Badge", link="https://www.codacy.com/public/lepetitfou_3463/poor-mans-lambda-test"]

Minimal Java8 Lambda enabled testing for TestNG (and later maybe JUnit).

== Motivation

When constrained to work in a Java-only toolchain, I really miss my http://scalatest.org[ScalaTest].
I tried some lambda enabled test frameworks, but until now, did not find a suitable solution without compromizing the integration benefits.

Thus I decided to hack a really small and generic base class that basically allows me write tests easier. Since then it evolved a bit but basically, it provides Lambda-enabled test and nice assert/expect constructs on top of an existing unit test framework (currently TestNG). 

== What you get

Most important features (beside all those you gain from using TestNG already) are:

* Write test via API (No longer required to have each test in a separate annotated method)
* Meaningful names for tests
* Easy to write data-centric tests (e.g. generate as much test cases as you need programmatically, e.g. in a loop)
* Opt-in to not fail fast when using `expectXXX`-methods (see more than the first assertion error)
* Easy to intercept exceptions
* Easy to mark pending tests
* Nice colored output per test case


== Download from Maven Central

LambdaTest is available from http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.tototec%22%20AND%20a%3A%22de.tobiasroeser.lambdatest%22[Maven central repository].

Maven users can use the following dependency declaration:

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>de.tototec</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>0.1.0</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.8</version>
    <scope>test</scope>
  </dependency>
</dependencies>
----

http://sbuild.org[SBuild] users can use the following dependencies:

[source,scala,subs="attributes"]
----
"mvn:de.tototoec:de.tobiasroeser.lambdatest:{lambdatestversion}" ~
  "mvn:org.testng:testng:6.8.8"
----


== Writing tests with Lambda Test

Here you see a basic test example, which produces a valid TestNG test class.
You need to extend from class `de.tobiasroeser.lambdatest.testng.FreeSpec`.

[source,java]
----
package org.example;

import static de.tobiasroeser.lambdatest.Expect.expectEquals;

import de.tobiasroeser.lambdatest.testng.FreeSpec;

class SimpleTest extends FreeSpec {{

  test("1 + 1 = 2", () -> {
    expectEquals(1 + 1, 2);
  });

  test("a pending test", () -> pending());

  test("divide by zero", () -> {
    int a = 2;
    int b = 0;
    intercept(ArithmeticException.class, () -> {
      int c = a / b;
    });
  });

}}
----

The methods `test`, `pending` and `intercept` are provided by `FreeSpec`
whereas the usual `expectXXX` methods are provided by `Expect`.

The output of this test suite above would look like this:

----
[TestNG] Running:
  Command line suite

Running 3 tests in org.example.SimpleTest:
-- SUCCESS SimpleTest: 1 + 1 = 2
-- SKIPPED SimpleTest: a pending test (pending)
-- SUCCESS SimpleTest: divide by zero

===============================================
Command line suite
Total tests run: 3, Failures: 0, Skips: 1
===============================================

----

You should write your test cases so that they don't need to be executed in order. LambdaTest is able to run tests in parallel, if you enable it explicitly with `FreeSpec.setRunInParallel(true)`.

You can disable fail fast behaviour for assertion/expectations with `FreeSpec.setExpectFailFast(false)`. Than, the first failing assertion error will non abort the test but the test is optimistically continued. Further failing assertion errors are collected and reported at the end of the test.

== Writing assertions with `Expect`

As an alternative to the assertion methods provides by other unit testing framework, you can instead use `Expect` and it's `expectXXX`-methods.

Why should you, you ask` Here are some reasons:

* Nice output of differences of various collections
* non-fail-fast behaviour to collect as much assertion errors as possible in one test run


_TBD_

=== Using `Expect` without `FreeSpec`

You can also use the `Expect` class outside of the `FreeSpec` test suites. 
In that case, you have to take care of setup and finalization yourself.

_TBD_

== Working on Java7 or below

This project does not use any Java 8 API!
So, it would be possible to use this test library on older Java Runtimes (down to Java5).
Currently, the binaries are compiled to Java8, Java7 and Java6. To use the non-Java8 version with Maven, use a classifier ("java7", or "java6") to download the version you want. The compatibility packages are produced with the great https://github.com/orfjackal/retrolambda[retrolambda project].

To use the Java7 version in Maven:

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>de.tototec</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>0.1.0</version>
    <classifier>java7</classifier>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.8</version>
    <scope>test</scope>
  </dependency>
</dependencies>
----

or in SBuild:

[source,scala,subs="attributes"]
----
"mvn:de.tototoec:de.tobiasroeser.lambdatest:{lambdatestversion};classifier=java7" ~
  "mvn:org.testng:testng:6.8.8"
----



Of course if you want to gain the benefits of using the nice Java 8 Closures a Java 8 compiler needs to be used.

== Licence

This project is published under the http://www.apache.org/licenses/LICENSE-2.0.txt[Apache Licence Version 2.0].

== Contribution

Feedback, reported issues and pull requests are highly appreciated. You can also find me on Twitter as https://twitter.com/TobiasRoeser[@TobiasRoeser].


== Changelog

=== 0.1.0 - 2014-12-08

* Also release compatibility packages for older Java runtimes: Java7 and Java6. They are available via the "java7" and "java6" classifier.
* FreeSpec.intercept now returns the intercepted exception.
* Added FreeSpec.setRunInParallel to enable option to run tests in parallel.
* Introduced LambdaTest interface (implemented by testng.FreeSpec) to contain the common API.

=== 2014-11-29

* Rerelease of 0.0.3 under "de.tototec" groupId. You can now grap it directly from Maven Central without configuring a dedicated bintray repositor.

=== 0.0.3 - 2014-11-16

* Fixed issue with missapplied close of STDOUT stream
* Fixed bug preventing from TestNG seeing pending tests as skipped
* de.tobiasroeser.lambdatest.testng.FreeSpec class no longer inherits org.testng.Assert

=== 0.0.2 - 2014-10-18

* Colored output
* Added support to match exception messages with regex in intecept

=== 0.0.1 - 2014-10-15

* First release
