= Lambda Test
:toc:
:toc-placement: preamble
:lambdatestversion: 0.2.0
:testngversion: 6.8.8
:junitversion: 4.11

image:https://travis-ci.org/lefou/LambdaTest.svg?branch=master["Build Status", link="https://travis-ci.org/lefou/LambdaTest"]
image:https://www.codacy.com/project/badge/b05b1dc99f98423eb05862de7fcf3662["Codacy Badge", link="https://www.codacy.com/public/lepetitfou_3463/LambdaTest"]
image:https://badges.gitter.im/lefou/LambdaTest.svg["Chat on Gitter", link="https://gitter.im/lefou/LambdaTest"]

Minimal Java8 Lambda enabled testing for JUnit and TestNG.

The latest released version is LambdaTest {lambdatestversion}.


_Please note, that this page might contain information about not yet released features._

== Motivation

When constrained to work in a Java-only toolchain, I really miss my http://scalatest.org[ScalaTest].
I tried some lambda enabled test frameworks, but until now, did not find a suitable solution without compromizing the integration benefits.

Thus I decided to hack a really small and generic base class that basically allows me write tests easier.
Since then it evolved a bit but basically, it provides Lambda-enabled test and nice assert/expect constructs on top of an existing unit test framework (JUnit or TestNG).

== Features

Most important features are:

* Write test via API (No longer required to have each test in a separate annotated method)
* Meaningful names for tests
* Easy to write data-centric tests (e.g. generate as much test cases as you need programmatically, e.g. in a loop)
* Easy to intercept exceptions
* Opt-in to not fail fast when using `expectXXX`-methods (see more than the first assertion error)
* Easy to mark pending tests
* Nice colored output per test case


== Download from Maven Central

LambdaTest is available from http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.tototec%22%20AND%20a%3A%22de.tobiasroeser.lambdatest%22[Maven central repository].

Maven users can use the following dependency declaration:

[source,xml,subs="attributes,verbatim"]
----
<dependencies>
  <dependency>
    <groupId>de.tototec</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>{lambdatestversion}</version>
    <scope>test</scope>
  </dependency>
  <!-- If you use LambdaTest with JUnit -->
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>{junitversion}</version>
    <scope>test</scope>
  </dependency>
  <!-- If you use LambdaTest with TestNG -->
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>{testngversion}</version>
    <scope>test</scope>
  </dependency>
</dependencies>
----

http://sbuild.org[SBuild] users can use the following dependencies:

.Use with JUnit
[source,scala,subs="attributes"]
----
"mvn:de.tototec:de.tobiasroeser.lambdatest:{lambdatestversion}" ~
  "mvn:junit:junit:{junitversion}"
----

.Use with TestNG
[source,scala,subs="attributes"]
----
"mvn:de.tototec:de.tobiasroeser.lambdatest:{lambdatestversion}" ~
  "mvn:org.testng:testng:{testngversion}"
----


== Writing tests with Lambda Test

Here you see a basic test example, which produces a valid TestNG test class.
You need to extend from class `de.tobiasroeser.lambdatest.testng.FreeSpec`.

[source,java]
----
import static de.tobiasroeser.lambdatest.Expect.expectEquals;
// You can also use JUnit based tests with
// import de.tobiasroeser.lambdatest.junit.FreeSpec;
import de.tobiasroeser.lambdatest.testng.FreeSpec;

class SimpleTest extends FreeSpec {
  public SimpleTest() {

  test("1 + 1 = 2", () -> {
    expectEquals(1 + 1, 2);
  });

  test("a pending test", () -> pending());

  test("divide by zero", () -> {
    int a = 2;
    int b = 0;
    intercept(ArithmeticException.class, () -> {
      int c = a / b;
    });
  });

}}
----

The methods `test`, `pending` and `intercept` are provided by `FreeSpec`
whereas the usual `expectXXX` methods are provided by `Expect`.

The output of this test suite above would look like this:
_(Actually it is also nicely coloured)_

----
[TestNG] Running:
  Command line suite

Running 3 tests in org.example.SimpleTest:
-- SUCCESS SimpleTest: 1 + 1 = 2
-- SKIPPED SimpleTest: a pending test (pending)
-- SUCCESS SimpleTest: divide by zero

===============================================
Command line suite
Total tests run: 3, Failures: 0, Skips: 1
===============================================

----

You should write your test cases so that they don't need to be executed in order.
LambdaTest is able to run tests in parallel, if you enable it explicitly with `FreeSpec.setRunInParallel(true)`.

You can disable fail fast behaviour for assertion/expectations with `FreeSpec.setExpectFailFast(false)`.
Then, the first failing assertion error will not abort the test but the test is optimistically continued. Further failing assertion errors are collected and reported at the end of the test.

== Writing assertions with `Expect`

As an alternative to the assertion methods provides by other unit testing framework, you can instead use `Expect` and it's `expectXXX`-methods.

Why should you, you ask? Here are some reasons:

* Nice output of differences of various collections
* optional non-fail-fast behaviour to collect as much assertion errors as possible in one test run


_TBD_

=== Using `Expect` without `FreeSpec`

You can also use the `Expect` class outside of the `FreeSpec` test suites.
In that case, you have to take care of setup and finalization yourself.

_TBD_

== Working on Java7 or below

Even though writing functional test makes most sence under Java 8,
there are enough reasons to also use them on older Java versions which do not provide nice closures.

LambdaTest does not use any Java 8 API! Therefore, there is nothing that stops you. You can download precompiled binaries of LambdaTest for older Java Runtimes down to Java 6.
To use the non-Java8 version with Maven, use a classifier ("java7", or "java6") to download the version you want.
The compatibility packages are produced with the great https://github.com/orfjackal/retrolambda[retrolambda project].

To use the Java7 version in Maven:

[source,xml,subs="attributes,verbatim"]
----
<dependencies>
  <dependency>
    <groupId>de.tototec</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>{lambdatestversion}</version>
    <classifier>java7</classifier>
    <scope>test</scope>
  </dependency>
  <!-- Also you need one of JUnit or TestNG, see above -->
</dependencies>
----

or in SBuild:

[source,scala,subs="attributes"]
----
"mvn:de.tototoec:de.tobiasroeser.lambdatest:{lambdatestversion};classifier=java7"
----

Instead of Java 8 Closures, you have to create anonymous classes.

[source,java]
----
import static de.tobiasroeser.lambdatest.Expect.expectEquals;
import de.tobiasroeser.lambdatest.RunnableWithException;
import de.tobiasroeser.lambdatest.junit.FreeSpec;

class SimpleTest extends FreeSpec {
  public SimpleTest() {

  test("1 + 1 = 2", new RunnableWithException() {
    public void run() throws Exception {
      expectEquals(1 + 1, 2);
    }
  });

  test("divide by zero", new RunnableWithException() {
    public void run() throws Exception {
      int a = 2;
      int b = 0;
      intercept(ArithmeticException.class, new RunnableWithException() {
        public void run() throws Exception {
          int c = a / b;
        }
      });
    }
  });

}}
----


== Licence

This project is published under the http://www.apache.org/licenses/LICENSE-2.0.txt[Apache Licence Version 2.0].

== Contribution

Your feedback is highly appreciated.

For questions please use the https://gitter.im/lefou/LambdaTest[Gitter chatroom].

To report issues or send pull request, use https://github.com/lefou/LambdaTest[GitHub].

You can also find me on https://twitter.com/TobiasRoeser[Twitter as @TobiasRoeser].

If you like LambdaTest, please star it on https://github.com/lefou/LambdaTest[GitHub]. This will help me to set my priorities. Thanks!

== Changelog

=== LambdaTest 0.2.0 - 2016-02-12

* Added JUnit support.
  You can now use `de.tobiasroeser.lambdatest.junit.FreeSpec` for JUnit based tests in addition to the already existing  `de.tobiasroeser.lambdatest.testng.FreeSpec` for TestNG based tests.
* Introduced new `Assert` and `Expect` classes. Expect-based asserts also support deferred exceptions. FreeSpec already integrates the setup of Expect.


=== LambdaTest 0.1.0 - 2014-12-08

* Also release compatibility packages for older Java runtimes: Java7 and Java6.
They are available via the "java7" and "java6" classifier.
* FreeSpec.intercept now returns the intercepted exception.
* Added FreeSpec.setRunInParallel to enable option to run tests in parallel.
* Introduced LambdaTest interface (implemented by testng.FreeSpec) to contain the common API.

=== Rerelease of LambdaTest 0.0.3 - 2014-11-29

* Rerelease of 0.0.3 under "de.tototec" groupId.
You can now grab it directly from Maven Central without configuring a dedicated bintray repository.

=== LambdaTest 0.0.3 - 2014-11-16

* Fixed issue with missapplied close of STDOUT stream
* Fixed bug preventing from TestNG seeing pending tests as skipped
* de.tobiasroeser.lambdatest.testng.FreeSpec class no longer inherits org.testng.Assert

=== LambdaTest 0.0.2 - 2014-10-18

* Colored output
* Added support to match exception messages with regex in intecept

=== LambdaTest 0.0.1 - 2014-10-15

* First release
