= poor-mans-lambda-test
:toc:
:toc-placement: preamble
// also update version in pom.xml example
:lambdatestversion: 0.0.3

image:https://travis-ci.org/lefou/poor-mans-lambda-test.svg?branch=master["Build Status", link="https://travis-ci.org/lefou/poor-mans-lambda-test"]
image:https://img.shields.io/codacy/b05b1dc99f98423eb05862de7fcf3662.svg["Codacy Badge", link="https://www.codacy.com/public/lepetitfou_3463/poor-mans-lambda-test"]

Minimal Java8 Lambda enabled testing for TestNG (and later maybe JUnit).

== Motivation

When constrained to work in a Java-only toolchain, I really miss my ScalaTest.
I tried some lambda enabled test frameworks, but until now,
I did not find a suitable solution without compromizing the integration benefits.

Thus I decided to hack a really small and generic base class that basically allows me write tests easier.
I avoided to develop a completely new test stack,
so for asserts and the like the tools of the underlying test framework (currently TestNG) are used. 

== What you get

Most important features (beside all those you gain from using TestNG already) are:

* No longer requied to have each test in a separate method
* Meaningful names for tests
* Easy to write data-centric tests (e.g. generate as much test cases as you need in a loop)
* Easy to intercept exceptions
* Easy to mark pending tests
* Nice colored output per test case


== Writing tests with Lambda Test

Here you see a basic test example, which produces a valid TestNG test class.
You need to extend from class `de.tobiasroeser.lambdatest.testng.FreeSpec`.

[source,java]
----
package org.example;

import static org.testng.Assert.assertEquals;

import de.tobiasroeser.lambdatest.testng.FreeSpec;

class SimpleTest extends FreeSpec {{

  test("1 + 1 = 2", () -> {
    assertEquals(1 + 1, 2);
  });

  test("a pending test", () -> pending());

  test("divide by zero", () -> {
    int a = 2;
    int b = 0;
    intercept(ArithmeticException.class, () -> {
      int c = a / b;
    });
  });

}}
----

The methods `test`, `pending` and `intercept` are provided by `FreeSpec`
whereas the usual `assertXXX` methods are provided by TestNG (in this case from `org.testng.Assert`).

The output of this test suite above would look like this:
----
[TestNG] Running:
  Command line suite

Running 3 tests in org.example.SimpleTest:
-- SUCCESS SimpleTest: 1 + 1 = 2
-- SKIPPED SimpleTest: a pending test (pending)
-- SUCCESS SimpleTest: divide by zero

===============================================
Command line suite
Total tests run: 3, Failures: 0, Skips: 1
===============================================

----

You should write your test cases so that they don't need to be executed in order.
Currently, TestNG has no option to run these tests in parallel, but this might change in future.

== Working on Java7 or below

This project does not use any Java 8 API!
So, it would be possible to use this test library on older Java Runtimes (down to Java5).
Currently, the binaries are compiled to Java8, but if you are interested in using it on Java7 or below, let me know or open a ticket, and I will create a new release that support it.
In such a case I would use the great retrolambda project do create compatible binaries.

Of course if you want to gain the benefits of using the nice Java 8 Closures a Java 8 compiler needs to be used.

== Licence

This project is published under the http://www.apache.org/licenses/LICENSE-2.0.txt[Apache Licence Version 2.0].

== Contribution

Feedback, reported issues and pull requests  are highly appreciated. You can also find me on Twitter as https://twitter.com/TobiasRoeser[@TobiasRoeser].

== Maven

To use this project in your Maven project:

[source,xml]
----
<dependencies>
  <dependency>
    <groupId>de.tototec</groupId>
    <artifactId>de.tobiasroeser.lambdatest</artifactId>
    <version>0.0.3</version>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.8.8</version>
    <scope>test</scope>
  </dependency>
</dependencies>
----

== Changelog

=== 2014-11-29

* Rerelease of 0.0.3 under "de.tototec" groupId. You can now grap it directly from Maven Central without configuring a dedicated bintray repositor.

=== 0.0.3 - 2014-11-16

* Fixed issue with missapplied close of STDOUT stream
* Fixed bug preventing from TestNG seeing pending tests as skipped
* de.tobiasroeser.lambdatest.testng.FreeSpec class no longer inherits org.testng.Assert

=== 0.0.2 - 2014-10-18

* Colored output
* Added support to match exception messages with regex in intecept

=== 0.0.1 - 2014-10-15

* First release
