on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [8, 11]

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.java-version == '11' && matrix.os == 'windows-latest' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - run: ./millw -i __.publishLocal testRepo
        if: matrix.os != 'windows-latest'
      - run: .\millw.bat -i __.publishLocal testRepo
        if: matrix.os == 'windows-latest'

      - run: ./millw -i -k __.testCached
        if: matrix.os != 'windows-latest'
      - run: ./millw.bat -i -k __.testCached
        if: matrix.os == 'windows-latest'
